"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 15:23:19.993091
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index('ix_api_usage_day_provider', ['day', 'provider'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('uploads_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('clip_min_seconds', sa.Float(), nullable=True),
    sa.Column('clip_max_seconds', sa.Float(), nullable=True),
    sa.Column('max_clips_per_video', sa.Integer(), nullable=True),
    sa.Column('min_video_minutes', sa.Float(), nullable=True),
    sa.Column('scan_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_analyze', sa.Boolean(), nullable=False),
    sa.Column('extra_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan_status', sa.String(length=32), nullable=True),
    sa.Column('last_scan_error', sa.Text(), nullable=True),
    sa.Column('last_scan_new_videos', sa.Integer(), nullable=False),
    sa.Column('last_video_published_at', sa.DateTime(), nullable=True),
    sa.Column('last_video_title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creators_youtube_channel_id'), ['youtube_channel_id'], unique=True)

    op.create_table('scoring_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('coefficients', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('feature_means', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_stds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('insights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_scoring_models_version')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_title', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('live_status', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.Column('prescore', sa.Float(), nullable=True),
    sa.Column('prescore_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('crowd_hotspots', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('media_key', sa.String(length=500), nullable=True),
    sa.Column('media_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('media_origin', sa.String(length=32), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_youtube_video_id'), ['youtube_video_id'], unique=True)

    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('models', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('candidates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_video_id'), ['video_id'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('word_timing', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('segments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('emphasis_words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('caption_preset', sa.String(length=32), nullable=True),
    sa.Column('layout', sa.String(length=32), nullable=True),
    sa.Column('render_key', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('render_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('render_error', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(length=16), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_rating'), ['rating'], unique=False)
        batch_op.create_index('ix_clips_score_created', ['viral_score', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_viral_score'), ['viral_score'], unique=False)

    op.create_table('clip_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_feedback_clip_id'), ['clip_id'], unique=False)

    op.create_table('clip_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('watch_time_seconds', sa.Float(), nullable=True),
    sa.Column('avg_watch_seconds', sa.Float(), nullable=True),
    sa.Column('avg_percentage_watched', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('followers_gained', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clip_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_performance_clip_id'), ['clip_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'priority', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_video_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_creator_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_clip_id'))
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    with op.batch_alter_table('clip_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_performance_clip_id'))

    op.drop_table('clip_performance')
    with op.batch_alter_table('clip_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_feedback_clip_id'))

    op.drop_table('clip_feedback')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_viral_score'))
        batch_op.drop_index(batch_op.f('ix_clips_video_id'))
        batch_op.drop_index(batch_op.f('ix_clips_status'))
        batch_op.drop_index('ix_clips_score_created')
        batch_op.drop_index(batch_op.f('ix_clips_rating'))
        batch_op.drop_index(batch_op.f('ix_clips_creator_id'))
        batch_op.drop_index(batch_op.f('ix_clips_created_at'))
        batch_op.drop_index(batch_op.f('ix_clips_category'))

    op.drop_table('clips')
    op.drop_table('transcripts')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_video_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_videos_status'))
        batch_op.drop_index(batch_op.f('ix_videos_published_at'))
        batch_op.drop_index(batch_op.f('ix_videos_creator_id'))

    op.drop_table('videos')
    op.drop_table('scoring_models')
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creators_youtube_channel_id'))

    op.drop_table('creators')
    op.drop_table('app_settings')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_api_usage_day_provider')

    op.drop_table('api_usage')
    # ### end Alembic commands ###
